server:
  port: 8080
spring:
  datasource:
    url: jdbc:hsqldb:hsql:/localhost:9001/db
    driverClassName: org.hsqldb.jdbcDriver
    username: root
    password: iyzico
  jpa:
    show-sql: true
    open-in-view: false
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration:

iyzico:
  pay:
    test:
      apiKey: "sandbox-Edr075BZdgLGqmHYrsdx9tV3HKIulWM7"
      secretKey: "sandbox-xFhP4fZaRB2qCwGqEdvqySVV7eZmuMOP"
      baseUrl: "https://sandbox-api.iyzipay.com"
